spring.application.name=fitness-tracker-api
spring.config.import=optional:file:.env[.properties]

# Security
security.enabled=true

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.bearer-token.expiration=900000
jwt.refresh-token.expiration=604800000

# Database
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File upload max size in bytes
media.max-file-size=10485760