spring.application.name=fitness-tracker-api
spring.config.import=optional:file:.env[.properties]

# Security
security.enabled=true

# JWT Configuration
# Add a .env file with a JWT_SECRET=<place-for-your-key> line for this to work
jwt.secret=${JWT_SECRET}
jwt.bearer-token.expiration=900000
jwt.refresh-token.expiration=604800000

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_tracker
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
